export type ValidationErrorCode =
  | "ERR_VALIDATION_INTEGER"
  | "ERR_VALIDATION_RUNTIME"
  | "ERR_VALIDATION_NETWORK_POLICY"
  | "ERR_VALIDATION_PORT"
  | "ERR_VALIDATION_PORT_CONFLICT"
  | "ERR_VALIDATION_DOMAIN"
  | "ERR_VALIDATION_CIDR"
  | "ERR_VALIDATION_IMAGE_REF"
  | "ERR_VALIDATION_DISK_SIZE"
  | "ERR_VALIDATION_DURATION"
  | "ERR_VALIDATION_FLAGS"
  | "ERR_VALIDATION_POLICY_CONFLICT";

export type VmErrorCode =
  | "ERR_VM_NOT_FOUND"
  | "ERR_VM_STATE_NOT_FOUND"
  | "ERR_VM_NOT_STOPPED"
  | "ERR_VM_NOT_RUNNING"
  | "ERR_VM_NO_AGENT_TOKEN"
  | "ERR_VM_CHROOT_NOT_FOUND"
  | "ERR_VM_NETWORK_SLOTS_EXHAUSTED"
  | "ERR_VM_SNAPSHOT_NOT_FOUND";

export type FirecrackerErrorCode = "ERR_FIRECRACKER_API";

export type NetworkErrorCode =
  | "ERR_NETWORK_DEFAULT_INTERFACE"
  | "ERR_NFT_SETUP_FAILED"
  | "ERR_NFT_TEARDOWN_FAILED"
  | "ERR_NFT_BINARY_MISSING"
  | "ERR_NFT_TABLE_MISSING";

export type TimeoutErrorCode = "ERR_TIMEOUT_SOCKET" | "ERR_TIMEOUT_LOCK" | "ERR_TIMEOUT_AGENT";

export type SetupErrorCode =
  | "ERR_SETUP_MISSING_BINARY"
  | "ERR_SETUP_NO_KERNEL_DIR"
  | "ERR_SETUP_NO_KERNEL"
  | "ERR_SETUP_NO_ROOTFS_DIR"
  | "ERR_SETUP_NO_EXT4_ROOTFS"
  | "ERR_SETUP_KVM_UNAVAILABLE";

export type CloudflareErrorCode =
  | "ERR_CLOUDFLARE_NOT_CONFIGURED"
  | "ERR_CLOUDFLARE_TUNNEL_NO_ID"
  | "ERR_CLOUDFLARE_BINARY_NOT_FOUND"
  | "ERR_CLOUDFLARE_CONFIG_NOT_FOUND"
  | "ERR_CLOUDFLARE_START_FAILED"
  | "ERR_CLOUDFLARE_NO_ACCOUNTS"
  | "ERR_CLOUDFLARE_NO_ZONE";

export type VmsanErrorCode =
  | ValidationErrorCode
  | VmErrorCode
  | FirecrackerErrorCode
  | NetworkErrorCode
  | TimeoutErrorCode
  | SetupErrorCode
  | CloudflareErrorCode;
