#!/usr/bin/env bun
// Generates shell completion scripts from the commands.ts manifest.
// Run via: bun run src/completions/codegen.ts  (or: bun run build)

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { CLI_NAME, GLOBAL_FLAGS, SUBCOMMANDS } from "./commands.ts";
import type { FlagDef, PositionalDef, SubcommandDef } from "./commands.ts";

const dir = dirname(fileURLToPath(import.meta.url));
const outDir = join(dir, "generated");
mkdirSync(outDir, { recursive: true });

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function subcmdFlagList(sub: SubcommandDef, subGlobal: FlagDef[]): string[] {
  const flags: string[] = [];
  for (const f of sub.flags) {
    flags.push("--" + f.long);
    if (f.short) flags.push("-" + f.short);
  }
  for (const g of subGlobal) flags.push("--" + g.long);
  return flags;
}

function collectEnumFlags(subcommands: SubcommandDef[]): Map<string, string[]> {
  const map = new Map<string, string[]>();
  for (const sub of subcommands) {
    for (const f of sub.flags) {
      if (f.choices && !map.has(f.long)) map.set(f.long, f.choices);
    }
  }
  return map;
}

// ---------------------------------------------------------------------------
// Bash
// ---------------------------------------------------------------------------

function generateBash(cliName: string, globalFlags: FlagDef[], subcommands: SubcommandDef[]): string {
  const U = cliName.toUpperCase().replace(/-/g, "_");
  const subGlobal = globalFlags.filter((f) => !f.topLevelOnly);
  const subcmdNames = subcommands.map((s) => s.name).join(" ");
  const enumFlags = collectEnumFlags(subcommands);

  let enumBlock = "";
  for (const [long, choices] of enumFlags) {
    enumBlock += "    --" + long + ")\n";
    enumBlock += '      COMPREPLY=($(compgen -W "' + choices.join(" ") + '" -- "$cur"))\n';
    enumBlock += "      return\n";
    enumBlock += "      ;;\n";
  }

  // Positional completion groups
  const variadicVmId = subcommands
    .filter((s) => s.positionals[0]?.completeWith === "vmId" && s.positionals[0]?.variadic)
    .map((s) => s.name);
  const nonVariadicVmId = subcommands
    .filter((s) => s.positionals[0]?.completeWith === "vmId" && !s.positionals[0]?.variadic)
    .map((s) => s.name);
  const shellPos = subcommands
    .filter((s) => s.positionals[0]?.completeWith === "shell")
    .map((s) => s.name);

  let positionalBlock = "";
  if (nonVariadicVmId.length > 0) {
    positionalBlock += "    " + nonVariadicVmId.join("|") + ")\n";
    positionalBlock += '      if [[ $cword -eq 2 && "$cur" != -* ]]; then\n';
    positionalBlock += '        COMPREPLY=($(compgen -W "$vm_ids" -- "$cur"))\n';
    positionalBlock += "        return\n";
    positionalBlock += "      fi\n";
    positionalBlock += "      ;;\n";
  }
  if (variadicVmId.length > 0) {
    positionalBlock += "    " + variadicVmId.join("|") + ")\n";
    positionalBlock += '      if [[ "$cur" != -* ]]; then\n';
    positionalBlock += '        COMPREPLY=($(compgen -W "$vm_ids" -- "$cur"))\n';
    positionalBlock += "        return\n";
    positionalBlock += "      fi\n";
    positionalBlock += "      ;;\n";
  }
  if (shellPos.length > 0) {
    positionalBlock += "    " + shellPos.join("|") + ")\n";
    positionalBlock += "      if [[ $cword -eq 2 ]]; then\n";
    positionalBlock += '        COMPREPLY=($(compgen -W "bash zsh fish powershell" -- "$cur"))\n';
    positionalBlock += "        return\n";
    positionalBlock += "      fi\n";
    positionalBlock += "      ;;\n";
  }

  // Flag completion cases per subcommand
  let flagBlock = "";
  for (const sub of subcommands) {
    const flags = subcmdFlagList(sub, subGlobal);
    flagBlock += "    " + sub.name + ")\n";
    flagBlock += '      COMPREPLY=($(compgen -W "' + flags.join(" ") + '" -- "$cur"))\n';
    flagBlock += "      ;;\n";
  }

  let out = "";
  out += "# " + cliName + " bash completion\n";
  out += "# Add to ~/.bashrc:\n";
  out += "#   eval \"$(" + cliName + " completion bash)\"\n";
  out += "# This file is generated by src/completions/codegen.ts — edit commands.ts to change it.\n";
  out += "\n";
  out += "_" + cliName + "_get_vm_ids() {\n";
  out += "  local " + cliName + '_dir="${' + U + '_DIR:-$HOME/.' + cliName + '}"\n';
  out += "  local vms_dir=\"$" + cliName + '_dir/vms"\n';
  out += '  if [[ -d "$vms_dir" ]]; then\n';
  out += '    for f in "$vms_dir"/*.json; do\n';
  out += '      [[ -f "$f" ]] || continue\n';
  out += '      local base="${f##*/}"\n';
  out += "      printf '%s\\n' \"${base%.json}\"\n";
  out += "    done\n";
  out += "  fi\n";
  out += "}\n";
  out += "\n";
  out += "_" + cliName + "_complete() {\n";
  out += "  local cur prev words cword\n";
  out += "  _init_completion 2>/dev/null || {\n";
  out += "    COMPREPLY=()\n";
  out += '    cur="${COMP_WORDS[COMP_CWORD]}"\n';
  out += '    prev="${COMP_WORDS[COMP_CWORD-1]}"\n';
  out += '    words=("${COMP_WORDS[@]}")\n';
  out += "    cword=$COMP_CWORD\n";
  out += "  }\n";
  out += "\n";
  out += '  local subcommands="' + subcmdNames + '"\n';
  out += "\n";
  out += "  if [[ $cword -eq 1 ]]; then\n";
  out += '    COMPREPLY=($(compgen -W "$subcommands" -- "$cur"))\n';
  out += "    return\n";
  out += "  fi\n";
  out += "\n";
  out += '  local subcmd="${words[1]}"\n';
  out += "\n";
  out += '  case "$prev" in\n';
  out += enumBlock;
  out += "  esac\n";
  out += "\n";
  out += "  local vm_ids\n";
  out += "  vm_ids=$(_" + cliName + "_get_vm_ids)\n";
  out += "\n";
  out += '  case "$subcmd" in\n';
  out += positionalBlock;
  out += "  esac\n";
  out += "\n";
  out += '  case "$subcmd" in\n';
  out += flagBlock;
  out += "  esac\n";
  out += "}\n";
  out += "\n";
  out += "complete -F _" + cliName + "_complete " + cliName + "\n";
  return out;
}

// ---------------------------------------------------------------------------
// Zsh
// ---------------------------------------------------------------------------

function generateZsh(cliName: string, globalFlags: FlagDef[], subcommands: SubcommandDef[]): string {
  const subGlobal = globalFlags.filter((f) => !f.topLevelOnly);
  const topLevel = globalFlags.filter((f) => f.topLevelOnly);

  // Global flags array for zsh _arguments
  let globalFlagsBlock = "";
  for (const f of subGlobal) {
    globalFlagsBlock += "    '--" + f.long + "[" + f.description + "]'\n";
  }
  for (const f of topLevel) {
    globalFlagsBlock += "    '(- :)--" + f.long + "[" + f.description + "]'\n";
  }

  // Subcommand list
  let subcmdList = "";
  for (const sub of subcommands) {
    subcmdList += "        '" + sub.name + ":" + sub.description + "'\n";
  }

  // Per-subcommand _arguments blocks
  function zshFlagSpec(f: FlagDef): string {
    const indent = "            ";
    if (f.short) {
      // Zsh brace expansion: '(-s --long)'{-s,--long}'[desc]'
      const prefix = "'(-" + f.short + " --" + f.long + ")'{-" + f.short + ",--" + f.long + "}'";
      if (f.takesArg) {
        let arg = "=[" + f.description + "]:";
        if (f.choices) arg += f.long + ":(" + f.choices.join(" ") + ")";
        else if (f.completeWith === "file") arg += f.long + ":_files";
        else arg += f.long;
        return indent + prefix + arg + "'";
      }
      return indent + prefix + "[" + f.description + "]'";
    } else {
      // Simple flag: '--long[desc]' or '--long=[desc]:arg'
      if (f.takesArg) {
        let arg = "=[" + f.description + "]:";
        if (f.choices) arg += f.long + ":(" + f.choices.join(" ") + ")";
        else if (f.completeWith === "file") arg += f.long + ":_files";
        else arg += f.long;
        return indent + "'--" + f.long + arg + "'";
      }
      return indent + "'--" + f.long + "[" + f.description + "]'";
    }
  }

  function zshPosSpec(pos: PositionalDef, index: number): string {
    const label = pos.description.toLowerCase().replace(/\s+/g, "-");
    const prefix = pos.variadic ? "*" : String(index);
    if (pos.completeWith === "vmId") return "            '" + prefix + ":" + label + ":_" + cliName + "_vm_ids'";
    if (pos.completeWith === "file") return "            '" + prefix + ":" + label + ":_files'";
    if (pos.completeWith === "shell") return "            '" + prefix + ":" + label + ":(bash zsh fish powershell)'";
    return "            '" + prefix + ":" + label + ":'";
  }

  let subcmdCases = "";
  for (const sub of subcommands) {
    subcmdCases += "        " + sub.name + ")\n";
    subcmdCases += "          _arguments \\\n";
    let posIdx = 1;
    for (const pos of sub.positionals) {
      subcmdCases += zshPosSpec(pos, posIdx) + " \\\n";
      if (!pos.variadic) posIdx++;
    }
    for (const f of sub.flags) {
      subcmdCases += zshFlagSpec(f) + " \\\n";
    }
    subcmdCases += "            $global_flags\n";
    subcmdCases += "          ;;\n";
  }

  let out = "";
  out += "#compdef " + cliName + "\n";
  out += "# " + cliName + " zsh completion\n";
  out += "# Add to ~/.zshrc:\n";
  out += "#   eval \"$(" + cliName + " completion zsh)\"\n";
  out += "# Or save directly to fpath:\n";
  out += "#   " + cliName + ' completion zsh > "${fpath[1]}/_' + cliName + '"\n';
  out += "# This file is generated by src/completions/codegen.ts — edit commands.ts to change it.\n";
  out += "\n";
  out += "_" + cliName + "_vm_ids() {\n";
  out += '  local ' + cliName + '_dir="${' + cliName.toUpperCase().replace(/-/g, "_") + '_DIR:-$HOME/.' + cliName + '}"\n';
  out += "  local vms_dir=\"$" + cliName + '_dir/vms"\n';
  out += "  local -a ids\n";
  out += '  if [[ -d "$vms_dir" ]]; then\n';
  out += "    for f in \"$vms_dir\"/*.json(N); do\n";
  out += '      ids+=("${${f##*/}%.json}")\n';
  out += "    done\n";
  out += "  fi\n";
  out += "  _describe 'VM ID' ids\n";
  out += "}\n";
  out += "\n";
  out += "_" + cliName + "() {\n";
  out += "  local context state state_descr line\n";
  out += "  typeset -A opt_args\n";
  out += "\n";
  out += "  local -a global_flags\n";
  out += "  global_flags=(\n";
  out += globalFlagsBlock;
  out += "  )\n";
  out += "\n";
  out += "  _arguments -C \\\n";
  out += "    $global_flags \\\n";
  out += "    '1:subcommand:->subcommand' \\\n";
  out += "    '*::args:->args'\n";
  out += "\n";
  out += "  case $state in\n";
  out += "    subcommand)\n";
  out += "      local -a subcmds\n";
  out += "      subcmds=(\n";
  out += subcmdList;
  out += "      )\n";
  out += "      _describe 'subcommand' subcmds\n";
  out += "      ;;\n";
  out += "    args)\n";
  out += "      case $line[1] in\n";
  out += subcmdCases;
  out += "      esac\n";
  out += "      ;;\n";
  out += "  esac\n";
  out += "}\n";
  out += "\n";
  out += "compdef _" + cliName + " " + cliName + "\n";
  return out;
}

// ---------------------------------------------------------------------------
// Fish
// ---------------------------------------------------------------------------

function generateFish(cliName: string, globalFlags: FlagDef[], subcommands: SubcommandDef[]): string {
  const subGlobal = globalFlags.filter((f) => !f.topLevelOnly);
  const allSubcmdNames = subcommands.map((s) => s.name).join(" ");
  const U = cliName.toUpperCase().replace(/-/g, "_");

  let out = "";
  out += "# " + cliName + " fish completion\n";
  out += "# Install permanently:\n";
  out += "#   " + cliName + " completion fish > ~/.config/fish/completions/" + cliName + ".fish\n";
  out += "# Or source temporarily in config.fish:\n";
  out += "#   " + cliName + " completion fish | source\n";
  out += "# This file is generated by src/completions/codegen.ts — edit commands.ts to change it.\n";
  out += "\n";
  out += "function __" + cliName + "_vm_ids\n";
  out +=
    '    set -l ' + cliName + '_dir (test -n "$' + U + '_DIR"; and echo "$' + U + '_DIR"; or echo "$HOME/.' + cliName + '")\n';
  out += "    set -l vms_dir \"$" + cliName + '_dir/vms"\n';
  out += "    if test -d \"$vms_dir\"\n";
  out += "        for f in $vms_dir/*.json\n";
  out += "            test -f \"$f\"; or continue\n";
  out += "            string replace -r '.*/([^/]+)\\.json$' '$1' \"$f\"\n";
  out += "        end\n";
  out += "    end\n";
  out += "end\n";
  out += "\n";
  out += "function __" + cliName + "_no_subcommand\n";
  out += "    not __fish_seen_subcommand_from " + allSubcmdNames + "\n";
  out += "end\n";
  out += "\n";
  out += "# Disable file completion globally; re-enabled per subcommand where needed\n";
  out += "complete -c " + cliName + " -f\n";
  out += "\n";
  out += "# Global flags\n";
  for (const f of subGlobal) {
    out += "complete -c " + cliName + " -l " + f.long + " -d '" + f.description + "'\n";
  }
  out += "\n";
  out += "# Subcommands\n";
  for (const sub of subcommands) {
    const pad = " ".repeat(Math.max(1, 10 - sub.name.length));
    out +=
      "complete -c " +
      cliName +
      " -n __" +
      cliName +
      "_no_subcommand -a " +
      sub.name +
      pad +
      "-d '" +
      sub.description +
      "'\n";
  }

  for (const sub of subcommands) {
    const hasFlags = sub.flags.length > 0;
    const hasVmId = sub.positionals.some((p) => p.completeWith === "vmId");
    const hasFilePos = sub.positionals.some((p) => p.completeWith === "file");
    const hasShellPos = sub.positionals.some((p) => p.completeWith === "shell");
    if (!hasFlags && !hasVmId && !hasFilePos && !hasShellPos) continue;

    out += "\n";
    out += "# " + sub.name + "\n";
    const cond = "'__fish_seen_subcommand_from " + sub.name + "'";

    if (hasVmId) {
      out += "complete -c " + cliName + " -n " + cond + " -a '(__" + cliName + "_vm_ids)' -d 'VM ID'\n";
    }

    for (const f of sub.flags) {
      let line = "complete -c " + cliName + " -n " + cond;
      if (f.short) line += " -s " + f.short;
      line += " -l " + f.long;
      line += " -d '" + f.description + "'";
      if (f.takesArg) {
        if (f.choices) {
          line += " -r -a '" + f.choices.join(" ") + "'";
        } else if (f.completeWith === "file") {
          line += " -rF";
        } else {
          line += " -r";
        }
      }
      out += line + "\n";
    }

    if (hasFilePos) {
      out += "complete -c " + cliName + " -n " + cond + " -F\n";
    }
    if (hasShellPos) {
      out +=
        "complete -c " + cliName + " -n " + cond + " -a 'bash zsh fish powershell' -d 'Shell'\n";
    }
  }
  out += "\n";
  return out;
}

// ---------------------------------------------------------------------------
// PowerShell
// ---------------------------------------------------------------------------

function generatePowerShell(
  cliName: string,
  globalFlags: FlagDef[],
  subcommands: SubcommandDef[],
): string {
  const U = cliName.toUpperCase().replace(/-/g, "_");
  const subGlobal = globalFlags.filter((f) => !f.topLevelOnly);
  const subcmdNames = subcommands.map((s) => "'" + s.name + "'").join(",");

  const enumFlags = collectEnumFlags(subcommands);

  // Build enum switch cases
  let enumBlock = "";
  for (const [long, choices] of enumFlags) {
    const choicesStr = choices.map((c) => "'" + c + "'").join(",");
    enumBlock += "        '--" + long + "' {\n";
    enumBlock += "            @(" + choicesStr + ") | Where-Object { $_ -like \"$wordToComplete*\" } | ForEach-Object {\n";
    enumBlock += "                [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)\n";
    enumBlock += "            }\n";
    enumBlock += "            return\n";
    enumBlock += "        }\n";
  }

  // Positional groups
  const variadicVmId = subcommands
    .filter((s) => s.positionals[0]?.completeWith === "vmId" && s.positionals[0]?.variadic)
    .map((s) => s.name);
  const nonVariadicVmId = subcommands
    .filter((s) => s.positionals[0]?.completeWith === "vmId" && !s.positionals[0]?.variadic)
    .map((s) => s.name);
  const shellPos = subcommands
    .filter((s) => s.positionals[0]?.completeWith === "shell")
    .map((s) => s.name);

  let positionalBlock = "";
  if (nonVariadicVmId.length > 0) {
    const match = nonVariadicVmId.map((n) => "'" + n + "'").join(",");
    positionalBlock += "        { $_ -in @(" + match + ") } {\n";
    positionalBlock += "            if ($positionals -eq 0 -and -not $wordToComplete.StartsWith('-')) {\n";
    positionalBlock += "                $vmIds | Where-Object { $_ -like \"$wordToComplete*\" } | ForEach-Object {\n";
    positionalBlock += "                    [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', \"VM ID: $_\")\n";
    positionalBlock += "                }\n";
    positionalBlock += "                return\n";
    positionalBlock += "            }\n";
    positionalBlock += "        }\n";
  }
  if (variadicVmId.length > 0) {
    const match = variadicVmId.map((n) => "'" + n + "'").join(",");
    positionalBlock += "        { $_ -in @(" + match + ") } {\n";
    positionalBlock += "            if (-not $wordToComplete.StartsWith('-')) {\n";
    positionalBlock += "                $vmIds | Where-Object { $_ -like \"$wordToComplete*\" } | ForEach-Object {\n";
    positionalBlock += "                    [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', \"VM ID: $_\")\n";
    positionalBlock += "                }\n";
    positionalBlock += "                return\n";
    positionalBlock += "            }\n";
    positionalBlock += "        }\n";
  }
  if (shellPos.length > 0) {
    const match = shellPos.map((n) => "'" + n + "'").join(",");
    positionalBlock += "        { $_ -in @(" + match + ") } {\n";
    positionalBlock += "            if (-not $wordToComplete.StartsWith('-')) {\n";
    positionalBlock += "                @('bash','zsh','fish','powershell') | Where-Object { $_ -like \"$wordToComplete*\" } | ForEach-Object {\n";
    positionalBlock += "                    [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)\n";
    positionalBlock += "                }\n";
    positionalBlock += "                return\n";
    positionalBlock += "            }\n";
    positionalBlock += "        }\n";
  }

  // $flagMap
  let flagMapBlock = "";
  for (const sub of subcommands) {
    const flags = subcmdFlagList(sub, subGlobal);
    flagMapBlock += "        '" + sub.name + "' = @(" + flags.map((f) => "'" + f + "'").join(",") + ")\n";
  }

  let out = "";
  out += "# " + cliName + " PowerShell completion\n";
  out += "# Add to your $PROFILE:\n";
  out += "#   Invoke-Expression (& " + cliName + " completion powershell | Out-String)\n";
  out += "# This file is generated by src/completions/codegen.ts — edit commands.ts to change it.\n";
  out += "\n";
  out += "function __" + cliName.replace(/-/g, "") + "_GetVmIds {\n";
  out +=
    "    $vmsanDir = if ($env:" + U + "_DIR) { $env:" + U + "_DIR } else { Join-Path $HOME '." + cliName + "' }\n";
  out += "    $vmsDir = Join-Path $vmsanDir 'vms'\n";
  out += "    if (Test-Path $vmsDir -PathType Container) {\n";
  out += "        Get-ChildItem -Path $vmsDir -Filter '*.json' | ForEach-Object { $_.BaseName }\n";
  out += "    }\n";
  out += "}\n";
  out += "\n";
  out += "Register-ArgumentCompleter -Native -CommandName " + cliName + " -ScriptBlock {\n";
  out += "    param($wordToComplete, $commandAst, $cursorPosition)\n";
  out += "\n";
  out += "    $tokens = @($commandAst.CommandElements | ForEach-Object { $_.ToString() })\n";
  out += "    $subcommands = @(" + subcmdNames + ")\n";
  out += "\n";
  out += "    $subcmd = $null\n";
  out += "    $subcmdIdx = -1\n";
  out += "    for ($i = 1; $i -lt $tokens.Count; $i++) {\n";
  out += "        if ($subcommands -contains $tokens[$i]) {\n";
  out += "            $subcmd = $tokens[$i]\n";
  out += "            $subcmdIdx = $i\n";
  out += "            break\n";
  out += "        }\n";
  out += "    }\n";
  out += "\n";
  out += "    # Complete subcommand name\n";
  out += "    if ($null -eq $subcmd) {\n";
  out += "        $subcommands | Where-Object { $_ -like \"$wordToComplete*\" } | ForEach-Object {\n";
  out += "            [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)\n";
  out += "        }\n";
  out += "        return\n";
  out += "    }\n";
  out += "\n";
  out += "    # Enum value completions for flags with fixed choices.\n";
  out += "    # When $wordToComplete is empty the current token is not yet in $tokens,\n";
  out += "    # so the preceding flag is at $tokens.Count - 1; when non-empty it is at\n";
  out += "    # $tokens.Count - 2.\n";
  out += "    $prevToken = if ($wordToComplete -eq '') {\n";
  out += "        if ($tokens.Count -ge 1) { $tokens[$tokens.Count - 1] } else { '' }\n";
  out += "    } else {\n";
  out += "        if ($tokens.Count -ge 2) { $tokens[$tokens.Count - 2] } else { '' }\n";
  out += "    }\n";
  out += "    switch ($prevToken) {\n";
  out += enumBlock;
  out += "    }\n";
  out += "\n";
  out += "    $vmIds = @(__" + cliName.replace(/-/g, "") + "_GetVmIds)\n";
  out += "\n";
  out += "    # Count positional (non-flag) tokens after the subcommand (excluding the current word)\n";
  out += "    $positionals = 0\n";
  out += "    for ($i = $subcmdIdx + 1; $i -lt $tokens.Count - 1; $i++) {\n";
  out += "        if (-not $tokens[$i].StartsWith('-')) { $positionals++ }\n";
  out += "    }\n";
  out += "\n";
  out += "    # Subcommand-specific positional completions\n";
  out += "    switch ($subcmd) {\n";
  out += positionalBlock;
  out += "    }\n";
  out += "\n";
  out += "    # Flag completions per subcommand\n";
  out += "    $flagMap = @{\n";
  out += flagMapBlock;
  out += "    }\n";
  out += "\n";
  out += "    if ($flagMap.ContainsKey($subcmd)) {\n";
  out += "        $flagMap[$subcmd] | Where-Object { $_ -like \"$wordToComplete*\" } | ForEach-Object {\n";
  out += "            [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterName', $_)\n";
  out += "        }\n";
  out += "    }\n";
  out += "}\n";
  return out;
}

// ---------------------------------------------------------------------------
// Write outputs
// ---------------------------------------------------------------------------

const shells = [
  {
    name: "bash",
    ext: "sh",
    content: generateBash(CLI_NAME, GLOBAL_FLAGS, SUBCOMMANDS),
    exportName: "bashCompletionScript",
  },
  {
    name: "zsh",
    ext: "sh",
    content: generateZsh(CLI_NAME, GLOBAL_FLAGS, SUBCOMMANDS),
    exportName: "zshCompletionScript",
  },
  {
    name: "fish",
    ext: "fish",
    content: generateFish(CLI_NAME, GLOBAL_FLAGS, SUBCOMMANDS),
    exportName: "fishCompletionScript",
  },
  {
    name: "powershell",
    ext: "ps1",
    content: generatePowerShell(CLI_NAME, GLOBAL_FLAGS, SUBCOMMANDS),
    exportName: "powershellCompletionScript",
  },
];

for (const { name, ext, content, exportName } of shells) {
  writeFileSync(join(outDir, name + "." + ext), content);
  console.log("  generated " + name + "." + ext);

  const ts =
    "// Generated by src/completions/codegen.ts — edit commands.ts, then run: bun run build\n" +
    "export const " +
    exportName +
    " = " +
    JSON.stringify(content) +
    ";\n";
  writeFileSync(join(outDir, name + ".ts"), ts);
  console.log("  generated " + name + ".ts");
}
